swagger: '2.0'
info:
  title: develop-portal-2.0
  version: '1.0'
host: '10.1.2.145:8501'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /service-profile:
    parameters: []
    get:
      summary: ''
      operationId: get-service-profile
      responses:
        '200':
          description: OK
          examples:
            example-1:
              resultCode: '20000'
              developerMessage: Success
              resultData:
                - partnerId: '963809917718806'
                  appName: 963809917718806jZokBg
                  displayName: test
                  displayDescription: test description
                  platformName: browser
                  appVersion: 1.0.0
                  appState: active
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                    - 'https://www.google.co.th'
                  accessTokenTime: 7200
                  serviceId: '672921'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-06-01 13:59:13'
                  createdBy: admin
                  updatedDate: '2021-06-01 13:59:13'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '935449627395788'
                  appName: 935449627395788SgMQM5
                  displayName: spectum
                  displayDescription: null
                  platformName: backend
                  appVersion: 1.0.0
                  appState: active
                  listOfApi: null
                  accessTokenTime: 3600
                  serviceId: '690286'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-06-01 13:51:29'
                  createdBy: admin
                  updatedDate: '2021-06-01 13:51:29'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '963809917718809'
                  appName: 963809917718809kKXFeS
                  displayName: WMTWT7
                  displayDescription: test description
                  platformName: browser
                  appVersion: 1.0.0
                  appState: active
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                    - 'https://www.google.co.th'
                  accessTokenTime: 7200
                  serviceId: '686020'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-06-01 09:34:29'
                  createdBy: admin
                  updatedDate: '2021-06-01 09:34:29'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '963809917718809'
                  appName: 963809917718809PBLt73
                  displayName: WMTWT3
                  displayDescription: test description
                  platformName: browser
                  appVersion: 1.0.0
                  appState: active
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                    - 'https://www.google.co.th'
                  accessTokenTime: 7200
                  serviceId: '620174'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-05-31 19:38:06'
                  createdBy: admin
                  updatedDate: '2021-05-31 19:38:06'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '963809917718809'
                  appName: 963809917718809BoH32e
                  displayName: test
                  displayDescription: test
                  platformName: backend
                  appVersion: 1.0.0
                  appState: active
                  listOfApi: null
                  accessTokenTime: 3600
                  serviceId: '697104'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-05-28 18:19:10'
                  createdBy: admin
                  updatedDate: '2021-05-28 18:19:10'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '963809917718802'
                  appName: 963809917718802iLO6NA
                  displayName: ac5
                  displayDescription: ac8
                  platformName: browser
                  appVersion: 1.0.0
                  appState: inactive
                  listOfApi:
                    - 'test/dummy:22222'
                  listOfRedirectUrl:
                    - 'https://www.google.co.th'
                  accessTokenTime: '9200'
                  serviceId: '614546'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-05-24 14:52:42'
                  createdBy: admin
                  updatedDate: '2021-05-28 16:45:13'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '915301585519804'
                  platformName: browser
                  appName: 932644850126902Hhjz5r
                  appVersion: 1.0.0
                  appState: active
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                    - 'https://www.google.co.th'
                  accessTokenTime: '20'
                  serviceId: '687829'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-04-08 15:18:09'
                  createdBy: admin
                  updatedDate: '2021-05-28 15:23:13'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                  displayName: mrfermz
                  displayDescription: aaaaaaaaaaa
                - partnerId: '963809917718807'
                  appName: 963809917718807c24VLJ
                  displayName: WMTWT3
                  displayDescription: test description
                  platformName: browser
                  appVersion: 1.0.0
                  appState: active
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                    - 'https://www.google.co.th'
                  accessTokenTime: 7200
                  serviceId: '611255'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-05-28 13:19:42'
                  createdBy: admin
                  updatedDate: '2021-05-28 13:19:42'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '932644850126981'
                  appName: 932644850126981MFOvOo
                  displayName: yo u
                  displayDescription: test description
                  platformName: browser
                  appVersion: 1.0.0
                  appState: active
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                    - 'https://www.google.co.th'
                  accessTokenTime: 7200
                  serviceId: '668875'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-05-28 11:32:24'
                  createdBy: admin
                  updatedDate: '2021-05-28 11:32:24'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
                - partnerId: '963809917718807'
                  appName: 9638099177188071sZBCw
                  displayName: '183'
                  displayDescription: '183'
                  platformName: browser
                  appVersion: 1.0.0
                  appState: inactive
                  listOfApi:
                    - 'test/dummy:11111'
                  listOfRedirectUrl:
                    - 'https://www.ais.co.th'
                  accessTokenTime: 3600
                  serviceId: '621902'
                  clientId: aZqfSPqPKgxe6CV5UEz00o5Il1xvW4hRGcH2gHh9DoU=
                  clientSecret: asjd9188882800
                  createdDate: '2021-05-28 10:35:20'
                  createdBy: admin
                  updatedDate: '2021-05-28 10:35:20'
                  updatedBy: admin
                  deletedDate: null
                  deletedBy: null
              rowCount: 28
      parameters:
        - type: string
          in: header
          name: Access-Control-Allow-Origin
          default: '*'
        - type: string
          in: header
          name: Access-Control-Allow-Methods
        - type: string
          in: header
          name: Access-Control-Allow-Headers
definitions:
  User:
    title: User
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for the given user.
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      dateOfBirth:
        type: string
        format: date
        example: '1997-10-31'
      emailVerified:
        type: boolean
        description: Set to true if the user's email has been verified.
      createDate:
        type: string
        format: date
        description: The date that the user was created.
    required:
      - id
      - firstName
      - lastName
      - email
      - emailVerified
basePath: /api/v1/pam
